#!/bin/bash
. /usr/share/htmlscript/helpers
if command -v kuser &>/dev/null; then
	pkexec kuser
else
	APP=$"Kuser"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf install --refresh --assumeyes kuser
	ProgressDialog --close
	if command -v kuser &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
