#!/bin/bash
. /usr/share/htmlscript/helpers
if which kuser &>/dev/null; then
	exec kuser
else
	APP=$"Kuser"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes kuser
	ProgressDialog --close
	if which kuser &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
