#!/bin/bash
. /usr/share/htmlscript/helpers

if command -v gimp &>/dev/null; then
exec gimp
else
	APP=$"GIMP"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes gimp
	ProgressDialog --close
	if rpm -qa |grep "^gimp"; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
