#!/bin/bash
. /usr/share/htmlscript/helpers

if rpm -q kraft; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Kraft is already installed.";
else
	APP=$"Kraft"
	ProgressDialog $"Installing $APP"
	enable-repo extra
	pkexec dnf --refresh install --assumeyes kraft
	ProgressDialog --close
	if rpm -q kraft; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
