#!/bin/bash
. /usr/share/htmlscript/helpers
if command -v rocs &>/dev/null; then
	exec rocs
else
	APP=$"Rocs"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes rocs
	ProgressDialog --close
	if command -v rocs &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
