#!/bin/bash
. /usr/share/htmlscript/helpers

if rpm -q inkscape; then
	exec inkscape
else
	APP=$"Inkscape"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes inkscape
	ProgressDialog --close
	if rpm -q inkscape; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
