#!/bin/bash
. /usr/share/htmlscript/helpers
if which lokalize &>/dev/null; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Lokalize is already installed."
else
	APP=$"Lokalize"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes lokalize
	ProgressDialog --close
	if which lokalize &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
