#!/bin/bash
. /usr/share/htmlscript/helpers
if command -v myrlyn &>/dev/null; then
	exec myrlyn-sudo
else
	APP=$"Myrlyn"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf install --refresh --assumeyes myrlyn
	ProgressDialog --close
	if command -v myrlyn &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
