#!/bin/bash
. /usr/share/htmlscript/helpers
if which nulloy &>/dev/null; then
	exec nulloy
else
	APP=$"Nulloy"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes nulloy
	ProgressDialog --close
	if which nulloy &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
