#!/bin/bash
. /usr/share/htmlscript/helpers
if which babe &>/dev/null; then
	exec babe
else
	APP=$"Babe"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes babe
	ProgressDialog --close
	if which babe &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
