#!/bin/bash
. /usr/share/htmlscript/helpers

	APP=$"nomacs"
if command -v nomacs; then
	kdialog --title $"OpenMandriva" --msgbox $"$APP is already installed."
else
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf install --refresh --assumeyes nomacs
	ProgressDialog --close
	if command -v nomacs; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
