#!/bin/bash
. /usr/share/htmlscript/helpers
if which bottles &>/dev/null; then
	exec bottles
else
	APP=$"Bottles"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes bottles
	ProgressDialog --close
	if which bottles &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
