#!/bin/bash
. /usr/share/htmlscript/helpers
if command -v yumex &>/dev/null; then
	exec yumex
else
	APP=$"Yumex"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes yumex
	ProgressDialog --close
	if command -v yumex &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
