#!/bin/bash
. /usr/share/htmlscript/helpers
if command -v audacity; then
	exec audacity
else
	APP=$"Audacity"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes audacity
	ProgressDialog --close
	if command -v audacity; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
