#!/bin/bash
. /usr/share/htmlscript/helpers
if which choqok; then
	exec choqok
else
	APP=$"Choqok"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes choqok
	ProgressDialog --close
	if which choqok; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
