#!/bin/bash
. /usr/share/htmlscript/helpers
if which step &>/dev/null; then
	exec step
else
	APP=$"Step"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes step
	ProgressDialog --close
	if which step &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
