#!/bin/bash
. /usr/share/htmlscript/helpers

if which homebank; then
	exec homebank
else
	APP=$"Homebank"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes homebank
	ProgressDialog --close
	if which homebank; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
