#!/bin/bash
. /usr/share/htmlscript/helpers
if command -v marknote; then
	exec marknote
else
	APP=$"Marknote"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes marknote
	ProgressDialog --close
	if command -v marknote; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
