#!/bin/bash
. /usr/share/htmlscript/helpers

if rpm -q maui-shell &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"MauiShell is already installed."
else
	enable-repo extra
	APP=$"MauiShell"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes maui-shell
	ProgressDialog --close
	if rpm -q maui-shell &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
