#!/bin/bash
. /usr/share/htmlscript/helpers

if command -v chromium; then
	exec chromium
else
	APP=$"Chromium"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes chromium
	ProgressDialog --close
	if command -v chromium; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
