#!/bin/bash
. /usr/share/htmlscript/helpers
if rpm -q calligra &>/dev/null; then
	exec calligra
else
	APP=$"Calligra"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes calligra*
	ProgressDialog --close
	if rpm -q calligra &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
