#!/bin/bash
. /usr/share/htmlscript/helpers
if command -v nheko &>/dev/null; then
	exec nheko
else
	APP=$"Nheko"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes nheko
	ProgressDialog --close
	if command -v nheko &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
