#!/bin/bash
. /usr/share/htmlscript/helpers

if command -v grsync; then
	exec grsync
else
	APP=$"GRsync"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	enable-repo extra
	pkexec dnf --refresh install --assumeyes grsync
	ProgressDialog --close
	if command -v grsync; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
