#!/bin/bash
. /usr/share/htmlscript/helpers
if rpm -qa |grep "blender*"; then
	exec blender
else
	APP=$"Blender"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes blender
	ProgressDialog --close
	if which blender; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
