#!/bin/bash
. /usr/share/htmlscript/helpers
if rpm -q dia; then
	exec dia
else
	APP=$"Dia"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes dia
	ProgressDialog --close
	if rpm -q dia; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
