#!/bin/bash
. /usr/share/htmlscript/helpers
if which lokalize &>/dev/null; then
	exec lokalize
else
	APP=$"Lokalize"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes lokalize
	ProgressDialog --close
	if which lokalize &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
