#!/bin/bash
. /usr/share/htmlscript/helpers
if which musescore &>/dev/null; then
	exec musescore
else
	APP=$"MuseScore"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes musescore
	ProgressDialog --close
	if which musescore &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
