#!/bin/bash
. /usr/share/htmlscript/helpers
if which cantor &>/dev/null; then
	exec cantor
else
	APP=$"Cantor"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes cantor
	ProgressDialog --close
	if which cantor &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
