#!/bin/bash
. /usr/share/htmlscript/helpers

if which qmmp; then
	exec qmmp
else
	APP=$"QMMP"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	enable-repo extra
	pkexec dnf install --assumeyes qmmp
	ProgressDialog --close
	if which qmmp; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
