#!/bin/bash
. /usr/share/htmlscript/helpers
if which proton &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"proton is already installed."
else
	APP=$"Proton"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes proton
	ProgressDialog --close
	if which proton &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
