#!/bin/bash
. /usr/share/htmlscript/helpers

if which gambas; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Gambas IDE is already installed."
else
	APP=$"Gambas IDE"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes gambas-ide
	ProgressDialog --close
	if which gambas; then
		kdialog --title $"OpenMandriva"  --msgbox  $" Gambas IDE successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" Gambas IDE not installed."
	fi
fi
