#!/bin/bash
. /usr/share/htmlscript/helpers
if which haruna &>/dev/null; then
	exec haruna
else
	APP=$"Haruna"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes haruna
	ProgressDialog --close
	if which haruna &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
