#!/bin/bash
. /usr/share/htmlscript/helpers
if which handbrake; then
	exec handbrake
else
	APP=$"HandBrake"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	enable-repo restricted
	pkexec dnf install --assumeyes handbrake
	ProgressDialog --close
	if which handbrake; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
