#!/bin/bash
. /usr/share/htmlscript/helpers
if which openshot-qt; then
	exec openshot-qt
else
	APP=$"OpenShot"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	enable-repo extra
	pkexec dnf install --assumeyes openshot
	ProgressDialog --close
	if which openshot-qt; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
