#!/bin/bash
. /usr/share/htmlscript/helpers

if which hardinfo2 &>/dev/null; then
	exec hardinfo2
else
	APP=$"Hardinfo2"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
    ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes hardinfo2
	ProgressDialog --close
	if which hardinfo2 &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
fi
