#!/bin/bash
. /usr/share/htmlscript/helpers
if which mscore &>/dev/null; then
	exec mscore
else
	APP=$"MuseScore"
	if kdialog --title $"OpenMandriva" --yesno $"Do you want to install $APP?"; then
		ProgressDialog $"Installing $APP"
		pkexec dnf install --assumeyes musescore
		ProgressDialog --close
		if which mscore &>/dev/null; then
			kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
		else
			kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
		fi
	fi
fi
